// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dognessnetwork.customer.dto;

import com.dognessnetwork.customer.dto.ChatMessage;
import io.springlets.format.EntityFormat;

privileged aspect ChatMessage_Roo_DTO {
    
    declare @type: ChatMessage: @EntityFormat;
    
}
