// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dognessnetwork.customer.dto;

import com.dognessnetwork.customer.dto.User;
import io.springlets.format.EntityFormat;

privileged aspect User_Roo_DTO {
    
    declare @type: User: @EntityFormat;
    
}
